"""Bottled waters by alkalinity band: which brands are near-zero-alkalinity diluents, which brew
like the SCA reference, which are as flat as hard tap water.

Run after `uv run wac build bottled-labels && uv run wac atlas`:
    uv run python scripts/bottled_report.py
Writes docs/bottled_waters_bands.md.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from water_aware_coffee.atlas.bands import BAND_NAMES, assign_band
from water_aware_coffee.model.grid import Grid, acid_lost_fraction
from water_aware_coffee.model.params import LIGHT

ROOT = Path(__file__).resolve().parents[1]
PROC = ROOT / "data" / "processed"
OUT = ROOT / "docs" / "bottled_waters_bands.md"

ROLE_RULES = (
    ("diluent (alkalinity under 15)", lambda a: a < 15),
    ("reference-like (25 to 60)", lambda a: 25 <= a <= 60),
    ("bright, softer than reference (15 to 25)", lambda a: 15 <= a < 25),
    ("moderate (60 to 150)", lambda a: 60 < a <= 150),
    ("flat, like hard tap water (over 150)", lambda a: a > 150),
)


def role(alk: float) -> str:
    for name, test in ROLE_RULES:
        if test(alk):
            return name
    return "unclassified"


def main() -> None:
    w = pd.read_parquet(PROC / "atlas_v0_wide.parquet")
    b = w[w["source_id"] == "bottled-labels"].copy()
    b["alk"] = pd.to_numeric(b["alkalinity_median"], errors="coerce")
    b["hard"] = pd.to_numeric(b["hardness_best"], errors="coerce")
    b["ph"] = pd.to_numeric(b["ph_median"], errors="coerce")
    b["ca"] = pd.to_numeric(b["calcium_median"], errors="coerce")
    b["mg"] = pd.to_numeric(b["magnesium_median"], errors="coerce")
    has_alk = b.dropna(subset=["alk"]).copy()
    has_alk["band"] = assign_band(has_alk["alk"])
    has_alk["band_name"] = has_alk["band"].map(dict(enumerate(BAND_NAMES, start=1)))
    grid = Grid(alkalinity_mgl=has_alk["alk"].to_numpy(), hardness_mgl=np.array([0.0]))
    has_alk["light_acid_lost"] = acid_lost_fraction(LIGHT, grid)[:, 0]
    has_alk["role"] = has_alk["alk"].map(role)
    lines = [
        "# Bottled waters by alkalinity band",
        "",
        "Generated by scripts/bottled_report.py from data/processed/atlas_v0_wide.parquet (source bottled-labels,",
        "data/external/bottled/bottled_waters_v0.csv). Alkalinity is bicarbonate × 0.820 (mg/L as CaCO3) or the printed",
        "'as CaCO3' value; hardness is Ca × 2.497 + Mg × 4.118 where both are printed. Declared label values, not samples.",
        "",
        f"{len(b)} products loaded; {len(has_alk)} with alkalinity; {int(b['hard'].notna().sum())} with hardness.",
        "",
        "## Roles for brewing (relative to the SCA reference of 40 mg/L alkalinity)",
        "",
        "| role | products | share of listed |",
        "|---|---|---|",
    ]
    rc = has_alk["role"].value_counts()
    for name, _ in ROLE_RULES:
        n = int(rc.get(name, 0))
        lines.append(f"| {name} | {n} | {n / len(has_alk):.0%} |")
    lines += [
        "",
        "## Products with alkalinity, by country (sorted by alkalinity)",
        "",
        "| country | brand and product | alkalinity mg/L as CaCO3 | hardness mg/L as CaCO3 | Ca | Mg | pH | band | light-roast acid lost | role |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for _, r in has_alk.sort_values(["country_iso2", "alk"]).iterrows():

        def f(x: float, nd: int = 0) -> str:
            return "" if pd.isna(x) else f"{x:.{nd}f}"

        lines.append(
            f"| {r['country_iso2']} | {r['locality']} | {r['alk']:.0f} | {f(r['hard'])} | {f(r['ca'], 1)} | {f(r['mg'], 1)} | {f(r['ph'], 1)} | "
            f"{int(r['band'])} | {r['light_acid_lost']:.0%} | {r['role']} |"
        )
    missing = b[b["alk"].isna()]
    lines += [
        "",
        f"## Products without alkalinity or bicarbonate on the label ({len(missing)})",
        "",
        ", ".join(sorted(missing["locality"].astype(str))),
        "",
        "## Notes",
        "",
        "- Diluents (alkalinity under 15) are what the dial-in rules mean by 'zero-alkalinity water' for blending hard tap water;",
        "  purified and remineralised US brands dominate this group.",
        "- Reference-like waters (25 to 60) brew any roast close to the model's reference; they are the natural 'control water'",
        "  for the community validation protocol because the same bottle is the same everywhere.",
        "- Waters over 150 mg/L (many European natural mineral waters) flatten coffee as much as hard tap water; they are the",
        "  ones a brewer should avoid for light roasts, whatever the marketing says.",
        "- Ranges printed by US brands ('18 - 200') were skipped, so some large US brands appear without alkalinity.",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{len(has_alk)} bottled products with alkalinity; roles: {rc.to_dict()}")


if __name__ == "__main__":
    main()
