"""Write docs/measurement-schema.md from provenance.MeasurementSchema.

Run: uv run python scripts/gen_schema_doc.py
"""

from __future__ import annotations

from pathlib import Path

from water_aware_coffee.provenance import MeasurementSchema
from water_aware_coffee.units import TARGET_UNIT

OUT = Path(__file__).resolve().parents[1] / "docs" / "measurement-schema.md"


def main() -> None:
    schema = MeasurementSchema.to_schema()
    lines = [
        "# Measurement table schema",
        "",
        "Generated by `scripts/gen_schema_doc.py` from `src/water_aware_coffee/provenance.py`.",
        "Do not edit by hand.",
        "",
        "Long format: one row per (place, period, quantity).",
        "`value` is always in the target unit for its quantity:",
        "",
        "| quantity | target unit |",
        "|---|---|",
        *[f"| {q.value} | {u} |" for q, u in TARGET_UNIT.items()],
        "",
        "| column | dtype | nullable | constraints | description |",
        "|---|---|---|---|---|",
    ]
    for name, col in schema.columns.items():
        checks = "; ".join(str(c.name or c) for c in col.checks) if col.checks else ""
        nullable = "yes" if col.nullable else "no"
        desc = col.description or ""
        lines.append(f"| `{name}` | {col.dtype} | {nullable} | {checks} | {desc} |")
    lines += [
        "",
        "Table-level checks:",
        "",
        *[f"- `{c.name}`" for c in schema.checks],
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
