"""Task 4 (bands): population share per alkalinity band by country, with the model's acid-loss
share at each band edge, plus docs/task4_bands_results.md and docs/task5_dialin_rules.md.

Run after `uv run wac bands`:  uv run python scripts/plot_task4_bands.py
"""

from __future__ import annotations

import ast
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

from water_aware_coffee.atlas.bands import BAND_NAMES  # noqa: E402
from water_aware_coffee.model.sensory import AdditiveSensory, rules_table  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
PROC = ROOT / "data" / "processed"
FIG = ROOT / "docs" / "figures"
INK, INK2, GRIDC, SURFACE = "#0b0b0b", "#52514e", "#e6e5e1", "#fcfcfb"
COUNTRY_COLOURS = {"US": "#2a78d6", "GB": "#eb6834", "BR": "#1baf7a"}
COUNTRY_NAMES = {
    "US": "United States, 3,341 cities with measured alkalinity",
    "GB": "England, 3 water companies with measured alkalinity",
    "BR": "Brazil, 2,441 municipalities, alkalinity imputed",
}

plt.rcParams.update(
    {
        "font.size": 10,
        "axes.edgecolor": INK2,
        "axes.labelcolor": INK,
        "xtick.color": INK2,
        "ytick.color": INK2,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "figure.facecolor": SURFACE,
        "axes.facecolor": SURFACE,
    }
)


def main() -> None:
    FIG.mkdir(parents=True, exist_ok=True)
    loc = pd.read_parquet(PROC / "bands_v0_localities.parquet")
    summary = pd.read_csv(PROC / "bands_v0_summary.csv")
    match = pd.read_csv(PROC / "matching_bands_v0.csv")
    edges = pd.read_csv(PROC / "bands_v0_edges.csv")

    # Population share per band within each country
    share = (
        (
            loc.groupby(["country_iso2", "band"])["weight"].sum()
            / loc.groupby("country_iso2")["weight"].sum()
        )
        .unstack("band")
        .fillna(0.0)
    )
    fig, ax = plt.subplots(figsize=(9.5, 4.8))
    x = np.arange(len(BAND_NAMES))
    w = 0.26
    for i, cc in enumerate(["US", "GB", "BR"]):
        if cc not in share.index:
            continue
        vals = [share.loc[cc].get(b, 0.0) for b in range(1, 6)]
        bars = ax.bar(
            x + (i - 1) * w,
            vals,
            width=w - 0.02,
            color=COUNTRY_COLOURS[cc],
            label=COUNTRY_NAMES[cc],
            linewidth=0,
        )
        for b, v in zip(bars, vals, strict=True):
            if v >= 0.04:
                ax.text(
                    b.get_x() + b.get_width() / 2,
                    v + 0.01,
                    f"{v:.0%}",
                    ha="center",
                    fontsize=8,
                    color=INK,
                )
    labels = [f"{n.split(' (')[0]}\n{n.split('(')[1].rstrip(')')} mg/L" for n in BAND_NAMES]
    ax.set_xticks(x)
    ax.set_xticklabels(labels, fontsize=8.5)
    ax.set_ylabel("share of the country's population")
    ax.set_ylim(0, 0.9)
    ax.yaxis.set_major_formatter(matplotlib.ticker.PercentFormatter(1.0))
    ax.legend(frameon=False, fontsize=9, loc="upper left")
    ax.grid(axis="y", color=GRIDC, linewidth=0.8)
    ax.set_axisbelow(True)
    # acid-loss annotations at band edges (light roast)
    for k, (e, lost) in enumerate(zip(edges.iloc[:, 0], edges.iloc[:, 1], strict=True)):
        ax.text(
            k + 0.5,
            0.60,
            f"{lost:.0%} of a light roast's\nacidity lost at {e:.0f} mg/L",
            ha="center",
            fontsize=7.5,
            color=INK2,
        )
    ax.set_title(
        "Who brews with which water: population share by alkalinity band (finished tap water, per country)",
        loc="left",
        fontsize=11,
        color=INK,
    )
    plt.close(fig)  # figure superseded by scripts/figures.py fig3; markdown below is still produced here

    # Task 4 results markdown
    lines = [
        "# Task 4 results (bands): water regimes as fixed alkalinity bands and matching table v0",
        "",
        "Generated by scripts/plot_task4_bands.py from data/processed/bands_v0_*.csv and matching_bands_v0.csv.",
        "Figure: docs/figures/task4_bands.png. Decision 29: bands replace the Gaussian mixture (regimes.py kept as an alternative).",
        "",
        "## Band edges and the model's acid-loss share (light roast, intrinsic TA 13.1 meq/L)",
        "",
        "| alkalinity edge (mg/L as CaCO3) | share of light-roast acidity neutralised |",
        "|---|---|",
        *[
            f"| {e:.0f} | {lost:.0%} |"
            for e, lost in zip(edges.iloc[:, 0], edges.iloc[:, 1], strict=True)
        ],
        "",
        "## Bands",
        "",
        "| band | localities | share of people (all) | share of people (measured alkalinity only) | alkalinity median (p10 to p90) | hardness median | softened share | imputed share | share of each country in this band |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for _, r in summary.iterrows():
        within = (
            ast.literal_eval(r["share_of_each_country_in_this_band"])
            if isinstance(r["share_of_each_country_in_this_band"], str)
            else r["share_of_each_country_in_this_band"]
        )
        within_s = ", ".join(f"{k} {v:.0%}" for k, v in within.items())
        lines.append(
            f"| {r['name']} | {int(r['localities']):,} | {r['population_share']:.0%} | {r['population_share_measured_only']:.0%} | "
            f"{r['alkalinity_median']:.0f} ({r['alkalinity_p10']:.0f} to {r['alkalinity_p90']:.0f}) | {r['hardness_median']:.0f} | "
            f"{r['share_softened']:.1%} | {r['share_imputed_alkalinity']:.0%} | {within_s} |"
        )
    lines += [
        "",
        "## Matching table v0 (relative residual acidity vs SCA reference water 40 / 68; 0.75 to 1.25 = works)",
        "",
        "| band | roast | at band median | at lower edge | at upper edge | parameter range at median | label at median | label at upper edge |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for _, m in match.iterrows():
        up = (
            ""
            if pd.isna(m["relative_residual_at_upper_edge"])
            else f"{m['relative_residual_at_upper_edge']:.2f}"
        )
        lines.append(
            f"| {int(m['band'])} | {m['roast']} | {m['relative_residual_at_median']:.2f} | {m['relative_residual_at_lower_edge']:.2f} | {up} | "
            f"{m['relative_residual_param_low']:.2f} to {m['relative_residual_param_high']:.2f} | {m['label_at_median']} | {m['label_at_upper_edge']} |"
        )
    lines += [
        "",
        "## Reading",
        "",
        "- Bands 1 to 3 (alkalinity up to 150 mg/L) are 'works' for every roast at their medians and edges: about 90 percent of people.",
        "- Band 4 (150 to 250) is 'compensate' for all roasts; band 5 (over 250) more so. Together about 10 percent of people",
        "  (12 percent on measured alkalinity only). Dark roast is hit hardest in relative terms in every band.",
        "- Brazil enters entirely through imputed alkalinity and is concentrated in bands 1 to 3; its band shares are model output, not measurement.",
        "- Softened water (hardness stripped, alkalinity kept) is rare overall but 6.5 percent of band 5.",
        "- The cation term is at its central value (zero) here. Liu 2025 suggests hardness may increase acidity for dark roasts;",
        "  the parameter range columns include the upper bound of that term.",
    ]
    (ROOT / "docs" / "task4_bands_results.md").write_text("\n".join(lines) + "\n")

    # Task 5 rules markdown
    sens = AdditiveSensory.from_frost_csv()
    rules = rules_table(sens, alkalinities=(20, 40, 80, 120, 150, 200, 250, 300))
    rules.to_csv(PROC / "dialin_rules_v0.csv", index=False)
    lines = [
        "# Task 5 results: dial-in rules v0",
        "",
        "Generated by scripts/plot_task4_bands.py; model in src/water_aware_coffee/model/sensory.py; table data/processed/dialin_rules_v0.csv.",
        "Reference water: alkalinity 40 mg/L as CaCO3 (SCA target). Recipe reference: TDS 1.25 percent, extraction 20 percent.",
        "",
        "Inputs: Batali et al. 2021 (TA by roast, TA linear in TDS, sourness 3.61 points per meq/L of TA);",
        "Frost et al. 2020 marginal means (sourness +21 points per percent TDS, -0.83 per percent extraction; bitterness +23 per",
        "percent TDS, +0.6 per percent extraction). Additive model, no interactions (decision 30).",
        "",
        "Three ways to compensate a water that flattens acidity, with what each costs:",
        "",
        "1. Strength: more coffee (or finer at constant extraction). Chemistry estimate restores titratable acidity; sensory estimate",
        "   restores predicted sourness; the truth is likely between them. Cost: bitterness and thickness rise with strength.",
        "2. Extraction: coarser grind or shorter contact. Cheap in bitterness (it falls too) but weak: 2 to 4 extraction points is the",
        "   realistic range, worth about 2 to 3 sourness points.",
        "3. Dilution: blend with zero-alkalinity water. Linear and free of side effects on the coffee; also lowers hardness.",
        "",
        "| roast | alkalinity (mg/L) | acid lost vs reference (meq/L) | sourness change (0 to 100) | TDS change, chemistry to sensory | dose change | bitterness side effect (chemistry route) | extraction change to fully restore | dilution share of zero-alkalinity water |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for _, r in rules.iterrows():
        lines.append(
            f"| {r['roast']} | {r['alkalinity_mgl']:.0f} | {r['acid_neutralised_meq_vs_ref']:+.2f} | {r['sourness_change_points']:+.1f} | "
            f"{r['tds_delta_percent_chemistry']:+.2f} to {r['tds_delta_percent_sensory']:+.2f} % | "
            f"{r['dose_change_percent_chemistry']:+.0f} to {r['dose_change_percent_sensory']:+.0f} % | "
            f"{r['bitterness_side_effect_tds_route']:+.1f} | {r['pe_delta_percent']:+.1f} points | {100 * r['dilution_share_zero_alkalinity_water']:.0f} % |"
        )
    lines += [
        "",
        "## Rules of thumb (v0, to be validated)",
        "",
        "- Each 50 mg/L of alkalinity above the SCA target removes about 1 meq/L of the brew's acid and about 3.6 sourness points",
        "  (a light roast starts near 37 on the 0 to 100 scale).",
        "- Up to about 100 mg/L: compensate by strength, +5 to +10 percent coffee per 40 mg/L above target, accepting slightly more bitterness.",
        "- 150 to 250 mg/L: strength alone costs 16 to 55 percent more coffee and +4 to +10 bitterness points; blend the water instead:",
        "  73 percent zero-alkalinity water at 150 mg/L, 84 percent at 250 mg/L, or use a low-alkalinity bottled water.",
        "- Below 40 mg/L (very soft or purified water) the coffee tastes sharper; use a little less coffee or extract a little more.",
        "- Dark roasts lose the largest share of their acidity to any given water, but they start with less to lose.",
        "",
        "Caveats: linear everywhere; sensory data are marginal means from one Honduran coffee; the two strength estimates differ by 1.8×;",
        "the cation term is zero here although Liu 2025 suggests hardness may raise dark-roast acidity; nothing here is validated by",
        "community brews yet.",
    ]
    (ROOT / "docs" / "task5_dialin_rules.md").write_text("\n".join(lines) + "\n")
    print("wrote task4_bands.png, task4_bands_results.md, task5_dialin_rules.md")


if __name__ == "__main__":
    main()
