"""Task 4 figure: water regimes on the alkalinity × hardness plane, one panel per regime
(small multiples, so no more than one categorical colour per panel), plus the BIC curve.

Run after `uv run wac regimes`:
    uv run python scripts/plot_task4_regimes.py
Writes docs/figures/task4_regimes.png and docs/task4_results.md.
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
PROC = ROOT / "data" / "processed"
FIG = ROOT / "docs" / "figures"
OUT_MD = ROOT / "docs" / "task4_results.md"

HIGHLIGHT = "#2a78d6"
OTHER = "#c9c8c3"
INK = "#0b0b0b"
INK2 = "#52514e"
GRIDC = "#e6e5e1"
SURFACE = "#fcfcfb"

plt.rcParams.update(
    {
        "font.size": 10,
        "axes.edgecolor": INK2,
        "axes.labelcolor": INK,
        "xtick.color": INK2,
        "ytick.color": INK2,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "figure.facecolor": SURFACE,
        "axes.facecolor": SURFACE,
    }
)


def main() -> None:
    FIG.mkdir(parents=True, exist_ok=True)
    loc = pd.read_parquet(PROC / "regimes_v0_localities.parquet")
    summary = pd.read_csv(PROC / "regimes_v0_summary.csv")
    match = pd.read_csv(PROC / "matching_v0.csv")
    model = json.loads((PROC / "regimes_v0_model.json").read_text())
    k = int(model["k"])

    ncols = 3
    nrows = int(np.ceil((k + 1) / ncols))
    fig, axes = plt.subplots(nrows, ncols, figsize=(12, 3.9 * nrows), sharex=False, sharey=False)
    axes = axes.ravel()
    measured = ~loc["alkalinity_imputed"].astype(bool)
    size = np.sqrt(loc["weight"].clip(lower=200, upper=2e6)) / 40
    for i in range(k):
        ax = axes[i]
        sel = loc["regime"] == i + 1
        ax.scatter(loc.loc[~sel, "hard"], loc.loc[~sel, "alk"], s=3, color=OTHER, linewidths=0)
        ax.scatter(
            loc.loc[sel & measured, "hard"],
            loc.loc[sel & measured, "alk"],
            s=size[sel & measured],
            color=HIGHLIGHT,
            alpha=0.6,
            linewidths=0,
            label="measured alkalinity",
        )
        ax.scatter(
            loc.loc[sel & ~measured, "hard"],
            loc.loc[sel & ~measured, "alk"],
            s=size[sel & ~measured],
            facecolors="none",
            edgecolors=HIGHLIGHT,
            alpha=0.6,
            linewidths=0.6,
            label="imputed alkalinity (Brazil)",
        )
        row = summary[summary["regime"] == i + 1].iloc[0]
        ax.set_title(
            f"Regime {i + 1}: {row['name']}\n{row['population_share']:.0%} of people, "
            f"{int(row['localities']):,} localities, {row['share_imputed_alkalinity']:.0%} imputed",
            loc="left",
            fontsize=9.5,
            color=INK,
        )
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_xlim(5, 1500)
        ax.set_ylim(3, 1000)
        ax.grid(color=GRIDC, linewidth=0.6)
        ax.set_axisbelow(True)
        if i % ncols == 0:
            ax.set_ylabel("alkalinity, mg/L as CaCO3")
        if i >= k - ncols or i >= (nrows - 1) * ncols:
            ax.set_xlabel("hardness, mg/L as CaCO3")
        if i == 0:
            ax.legend(loc="lower right", fontsize=8, frameon=False, markerscale=2)
    axb = axes[k]
    ks = [int(x) for x in model["bic"]]
    bics = [model["bic"][str(x)] for x in ks]
    axb.plot(ks, bics, color=INK, linewidth=2, marker="o", markersize=6)
    axb.set_xlabel("number of regimes k")
    axb.set_ylabel("population-weighted BIC")
    axb.set_title(
        f"BIC by k (effective sample size {model['n_eff']:,.0f}; cap at {max(ks)})",
        loc="left",
        fontsize=9.5,
        color=INK,
    )
    axb.grid(color=GRIDC, linewidth=0.6)
    axb.set_axisbelow(True)
    for j in range(k + 1, len(axes)):
        axes[j].axis("off")
    fig.suptitle(
        "Water regimes (Gaussian mixture on log alkalinity and log hardness, population-weighted; "
        "fitted on measured US and UK localities, Brazil classified). Dot area ∝ population.",
        x=0.01,
        ha="left",
        fontsize=11,
        color=INK,
    )
    fig.tight_layout(rect=(0, 0, 1, 0.95))
    fig.savefig(FIG / "task4_regimes.png", dpi=150)
    plt.close(fig)

    # Results markdown
    lines = [
        "# Task 4 results: water regimes and matching table v0",
        "",
        "Generated by scripts/plot_task4_regimes.py from data/processed/regimes_v0_*.{csv,json,parquet} and",
        "data/processed/matching_v0.csv. Figure: docs/figures/task4_regimes.png.",
        "",
        f"k = {k} regimes chosen by population-weighted BIC (effective sample size {model['n_eff']:,.0f}), "
        f"cap {max(ks)}. BIC by k: "
        + ", ".join(f"{a}: {b:,.0f}" for a, b in zip(ks, bics, strict=True))
        + ".",
        "",
        "## Regimes",
        "",
        "| regime | name | localities | share of people | alkalinity median (p10 to p90) | hardness median | imputed alkalinity share | population by country | examples (largest by population) |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for _, r in summary.iterrows():
        lines.append(
            f"| {int(r['regime'])} | {r['name']} | {int(r['localities']):,} | {r['population_share']:.0%} | "
            f"{r['alkalinity_median']:.0f} ({r['alkalinity_p10']:.0f} to {r['alkalinity_p90']:.0f}) | "
            f"{r['hardness_median']:.0f} | {r['share_imputed_alkalinity']:.0%} | {r['country_population_shares']} | "
            f"{r['examples_by_population']} |"
        )
    lines += [
        "",
        "## Matching table (relative residual acidity vs SCA reference water; 0.75 to 1.25 = works)",
        "",
        "| regime | roast | central | parameter range | across regime's alkalinity p10 to p90 | label | label stable across parameter range |",
        "|---|---|---|---|---|---|---|",
    ]
    for _, m in match.iterrows():
        lines.append(
            f"| {int(m['regime'])} | {m['roast']} | {m['relative_residual_central']:.2f} | "
            f"{m['relative_residual_param_low']:.2f} to {m['relative_residual_param_high']:.2f} | "
            f"{m['relative_residual_at_regime_p90_alk']:.2f} to {m['relative_residual_at_regime_p10_alk']:.2f} | "
            f"{m['label']} | {'yes' if m['label_stable_across_params'] else 'no'} |"
        )
    OUT_MD.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
